### PR TITLE
update dependencies, simplify build process

### PR DESCRIPTION
**Pull request by derhuerst**
This PR intends to bring the great geopattern up to date, regarding dependencies & build best practices. It also removed unnecessary stuff.

### CODE REVIEW

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by btmills** [comment]
Sorry for the delay in getting this reviewed, and thank you for contributing! There are a lot of unrelated changes for this being a single PR. Can you break this up into multiple separate PRs? Specifically, I'd like to see:

1. :+1: Remove `.npmignore` and use `package.json` `files` instead.
1. :+1: Remove the unnecessary `node_modules` paths in `package.json` `scripts`.
1. I used Gulp for the build system primarily because it made supported watching for changes and automatically rebuilding in the background. I'll consider a PR that removes Gulp, provided there's a good reason and that's still supported somehow.
1. As much as I'd like to use `Object.assign` instead of `extend`, that'd be a breaking change. If you still want to propose the change, we can discuss it in a PR. Including a polyfill would be a viable alternative here.
1. Updating dependencies is great, as long as it's done carefully. I know off the top of my head, for example, that ESLint v3 is incompatible with v0.10. I'll welcome PRs to update dependencies as long as they address incompatibilities. (In the case of ESLint specifically, the easiest way will be to extend `@btmills/eslint-config-btmills@beta`, which will avoid having to create a whole new config.)

Again, thank you for putting this together. As separate PRs, the changes will be much easier to review, meaning it won't take so long for me to get to them! :grin:

**Comment by derhuerst** [comment]
> As much as I'd like to use `Object.assign` instead of `extend`, that'd be a breaking change. If you still want to propose the change, we can discuss it in a PR. Including a polyfill would be a viable alternative here.

Fair enough. What about [`object-assign`](https://github.com/sindresorhus/object-assign)?

**Comment by derhuerst** [comment]
> I used Gulp for the build system primarily because it made supported watching for changes and automatically rebuilding in the background. I'll consider a PR that removes Gulp, provided there's a good reason and that's still supported somehow.

Would [`watchify`](https://github.com/substack/watchify) be an alternative sufficient to you?

**Comment by btmills** [comment]
Sure, both of those look good!

**Comment by btmills** [comment]
This was superseded by #26.

**Pull request closed without merging**
